/* Generated by Nim Compiler v1.6.8 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3   -I/home/marcelo/.choosenim/toolchains/nim-1.6.8/lib -I/home/marcelo/Documents/codigos/Nim/testes/tests -o /home/marcelo/Documents/codigos/Nim/testes/nimcache/tests/teste1.nim_4a8a08f09d37b73795649038408b5f33/@m..@ssrc@smain.nim.c.o /home/marcelo/Documents/codigos/Nim/testes/nimcache/tests/teste1.nim_4a8a08f09d37b73795649038408b5f33/@m..@ssrc@smain.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_2997)(void);
static N_INLINE(void, popFrame)(void);
extern TFrame* framePtr__system_2564;
extern TFrame* framePtr__system_2564;
extern TFrame* framePtr__system_2564;
extern TFrame* framePtr__system_2564;
extern TFrame* framePtr__system_2564;
extern TFrame* framePtr__system_2564;
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_2564 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_2564).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_2564;
	framePtr__system_2564 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_2997();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_2564 = (*framePtr__system_2564).prev;
}
N_LIB_PRIVATE N_NIMCALL(NI, soma2__OOZsrcZmain_1)(NI num) {
	NI result;
	NI TM__V45tF8B8NBcxFcjfe7lhBw_2;
	nimfr_("soma2", "/home/marcelo/Documents/codigos/Nim/testes/src/main.nim");
	result = (NI)0;
	nimln_(2, "/home/marcelo/Documents/codigos/Nim/testes/src/main.nim");
	if (nimAddInt(num, ((NI) 2), &TM__V45tF8B8NBcxFcjfe7lhBw_2)) { raiseOverflow(); };
	result = (NI)(TM__V45tF8B8NBcxFcjfe7lhBw_2);
	popFrame();
	return result;
}
